export const TEMPLATE_DATA = {
  en: {
    greeting: "Hi, I'm",
    view_work: 'View My Work',
    contact_me: 'Contact Me',
    home: 'Home',
    about: 'About',
    about_me: 'About Me',
    skills: 'Skills',
    projects: 'Projects',
    contact: 'Contact',
    name: 'Name',
    email: 'Email',
    experience: 'Experience',
    location: 'Location',
    years: 'years',
    pdf: 'Download CV PDF',
    my_skills: 'My Skills',
    my_projects: 'My Projects',
    live_demo: 'Live Demo',
    code: 'Code',
    get_in_touch: 'Get In Touch',
    lets_talk: 'Let´s talk about your project',
    contact_msg:
      "Feel free to reach out if you're looking for a developer, have a question, or just want to connect.",
    placeholder_name: 'Your Name',
    placeholder_email: 'Your Email',
    placeholder_subject: 'Subject',
    placeholder_msg: 'Your Message',
    send_msg: 'Send Message',
    rights: 'All rights reserved.',
    portfolio: 'Portfolio',
    dark_mode: 'Dark Mode',
    light_mode: 'Light Mode',
    whatsapp:
      'https://wa.me/5216143038485?text=Hi%20there,%20I%20saw%20your%20portfolio%20and%20wanted%20to%20connect',
    chat: 'Chat with me!',
    phone_img: 'assets/phone.png',
    email_img: 'assets/email.png',
    git_img: 'assets/git.png',
    portfolio_img: 'assets/portfolio_icon.png',
    c_education: 'EDUCATION',
    c_skills: 'SKILLS',
    c_profile: ' PROFILE',
    c_experience: 'WORK EXPERIENCE',
    c_languages: 'LANGUAGES',
    coreStack: [
      { name: 'Angular 18', level: 'expert' },
      { name: 'TypeScript', level: 'expert' },
      { name: 'Signals', level: 'expert' },
      { name: 'RxJS', level: 'expert' },
      { name: 'SCSS', level: 'mid' },
    ],
  },
  es: {
    greeting: 'Hola, Soy',
    view_work: 'Ve mi trabajo',
    contact_me: 'Contáctame',
    home: 'Inicio',
    about: 'Acerca de mí',
    about_me: 'Acerca de mí',
    skills: 'Habilidades',
    projects: 'Proyectos',
    contact: 'Contacto',
    name: 'Nombre',
    email: 'correo electrónico',
    experience: 'Experiencia',
    location: 'Ubicación',
    years: 'años',
    pdf: 'Descargar CV PDF',
    my_skills: 'Mis habilidades',
    my_projects: 'Mis Proyectos',
    live_demo: 'Demo',
    code: 'Código',
    get_in_touch: 'Ponte en Contacto',
    lets_talk: 'Hablemos de tu proyecto',
    contact_msg:
      'No dudes en comunicarte con nosotros si estás buscando un desarrollador, tienes alguna pregunta o simplemente quieres conectarte.',
    placeholder_name: 'Tu Nombre',
    placeholder_email: 'Tu Correo',
    placeholder_subject: 'Asunto',
    placeholder_msg: 'Tu mensaje',
    send_msg: 'Enviar Mensaje',
    rights: 'Todos los derechos reservados.',
    portfolio: 'Portafolio',
    dark_mode: 'Modo Oscuro',
    light_mode: 'Modo Claro',
    whatsapp:
      'https://wa.me/5216143038485?text=Hola,%20vi%20tu%20portafolio%20y%20me%20gustaría%20platicar',
    chat: '¡Hablemos!',
    phone_img: 'assets/phone.png',
    email_img: 'assets/email.png',
    git_img: 'assets/git.png',
    portfolio_img: 'assets/portfolio_icon.png',
    c_education: 'EDUCACION',
    c_skills: 'HABILIDADES',
    c_profile: 'PERFIL',
    c_experience: 'EXPERIENCIA LABORAL',
    c_languages: 'IDIOMAS',
    coreStack: [
      { name: 'Angular 18', level: 'expert' },
      { name: 'TypeScript', level: 'expert' },
      { name: 'Signals', level: 'expert' },
      { name: 'RxJS', level: 'expert' },
      { name: 'SCSS', level: 'mid' },
    ],
  },
};
